name: minetest-luk3yx-dev
version: "git"
summary: "luk3yx's unofficial Minetest builds."
description: |
  Minetest is a Minecraft-inspired game written from scratch and licensed
  under the LGPL (version 2.1 or later). It supports both survival and
  creative modes along with multiplayer support, dynamic lighting, and an
  "infinite" map generator.
grade: devel
confinement: strict
icon: snap/gui/minetest.svg
base: core18

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: i386
  - build-on: ppc64el

apps:
  minetest:
    command: launcher
    plugs: [desktop, desktop-legacy, x11, network, network-bind, opengl,
        audio-playback]
  minetestserver:
    command: launcher --server
    plugs: [desktop, desktop-legacy, x11, network, network-bind, opengl,
        audio-playback]
  minetest-luk3yx-dev:
    command: launcher
    plugs: [desktop, desktop-legacy, x11, network, network-bind, opengl,
        audio-playback]

parts:
  launcher:
    source: scripts
    plugin: dump
  minetestgame:
    source: https://github.com/minetest/minetest_game.git
    plugin: dump
    source-branch: master
    organize:
      '*': 'share/minetest/games/minetest_game/'
  irrlicht:
    source: https://github.com/minetest/irrlicht.git
    source-branch: master
    plugin: cmake
    override-pull: |
      snapcraftctl pull
      tag=$(git describe --tags $(git rev-list --tags --max-count=1))
      git checkout "$tag"

      curl https://github.com/appgurueu/irrlicht/commit/0f1bff1da4e38daeee944ff12d1a916373cdfbc2.patch > line-drawing.patch
      echo 'f54cea7dd9f18ddcda6a7f5e80c3e0f8c4256f8eb2ee5779f80084ef5c1652f7 line-drawing.patch' | sha256sum -c && git apply line-drawing.patch
      curl https://github.com/luk3yx/irrlicht/commit/66bdf09885cbf909e642d60f5be2797e21321ea2.patch > line-drawing-2.patch
      echo '4b50a56fb8777a5a1602494d1840a3b726a95ff56985b7bf67f4a8dce4bcbb6d line-drawing-2.patch' | sha256sum -c && git apply line-drawing-2.patch
      rm -v line-drawing.patch line-drawing-2.patch
  minetest:
    source: https://github.com/minetest/minetest.git
    source-branch: master
    plugin: cmake
    configflags: [-DRUN_IN_PLACE=FALSE]
    after:
      - irrlicht
    build-packages:
      - cmake
      - curl
      - gcc
      - g++
      - gettext
      - libcurl4-gnutls-dev
      - libfreetype6-dev
      - libglu1-mesa-dev
      - libjpeg-dev
      - libleveldb-dev
      - libluajit-5.1-dev
      - libogg-dev
      - libopenal-dev
      - libpng-dev
      - libpulse-dev
      - libsqlite3-dev
      - libvorbis-dev
      - libxi-dev
      - libx11-dev
      - libzstd-dev
      - zlib1g-dev
    stage-packages:
      - libgl1-mesa-dri
      - libpulse0
      - libcurl3-gnutls
      - libgl1-mesa-glx
      - libxshmfence1
      - libxcb-sync1
      - libxcb-present0
      - libxcb-glx0
      - libxcb-dri3-0
      - libxcb-dri2-0
      - libvorbisfile3
      - libsnappy1v5
      - libfreetype6
      - libopenal1
      - libluajit-5.1-2
      - libleveldb1v5
      - libjpeg-turbo8
      - libxxf86vm1
      - libxfixes3
      - libxext6
      - libxdamage1
      - libxi
      - libx11-6
      - libx11-xcb1
